# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GHEtool(object):
    def setupUi(self, GHEtool):
        GHEtool.setObjectName("GHEtool")
        GHEtool.resize(918, 911)
        GHEtool.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(0, 64, 122);")
        self.gridLayout_3 = QtWidgets.QGridLayout(GHEtool)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_Scenario = QtWidgets.QComboBox(GHEtool)
        self.comboBox_Scenario.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_Scenario.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_Scenario.setFont(font)
        self.comboBox_Scenario.setObjectName("comboBox_Scenario")
        self.horizontalLayout_3.addWidget(self.comboBox_Scenario)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_SaveScenario = QtWidgets.QPushButton(GHEtool)
        self.pushButton_SaveScenario.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_SaveScenario.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButton_SaveScenario.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_SaveScenario.setObjectName("pushButton_SaveScenario")
        self.horizontalLayout_3.addWidget(self.pushButton_SaveScenario)
        self.pushButton_AddScenario = QtWidgets.QPushButton(GHEtool)
        self.pushButton_AddScenario.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_AddScenario.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButton_AddScenario.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_AddScenario.setObjectName("pushButton_AddScenario")
        self.horizontalLayout_3.addWidget(self.pushButton_AddScenario)
        self.pushButton_DeleteScenario = QtWidgets.QPushButton(GHEtool)
        self.pushButton_DeleteScenario.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_DeleteScenario.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButton_DeleteScenario.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_DeleteScenario.setObjectName("pushButton_DeleteScenario")
        self.horizontalLayout_3.addWidget(self.pushButton_DeleteScenario)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_General = QtWidgets.QPushButton(GHEtool)
        self.pushButton_General.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_General.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_General.setObjectName("pushButton_General")
        self.verticalLayout_3.addWidget(self.pushButton_General)
        self.pushButton_thermalDemands = QtWidgets.QPushButton(GHEtool)
        self.pushButton_thermalDemands.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_thermalDemands.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_thermalDemands.setObjectName("pushButton_thermalDemands")
        self.verticalLayout_3.addWidget(self.pushButton_thermalDemands)
        self.pushButton_Results = QtWidgets.QPushButton(GHEtool)
        self.pushButton_Results.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_Results.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_Results.setObjectName("pushButton_Results")
        self.verticalLayout_3.addWidget(self.pushButton_Results)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(GHEtool)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_General = QtWidgets.QWidget()
        self.page_General.setObjectName("page_General")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_General)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_General = QtWidgets.QScrollArea(self.page_General)
        self.scrollArea_General.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_General.setLineWidth(0)
        self.scrollArea_General.setWidgetResizable(True)
        self.scrollArea_General.setObjectName("scrollArea_General")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 774, 753))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setStyleSheet("font: 75 16pt \"Arial\";")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_k_s = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_k_s.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_k_s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_k_s.setDecimals(3)
        self.doubleSpinBox_k_s.setMinimum(1.0)
        self.doubleSpinBox_k_s.setMaximum(100.0)
        self.doubleSpinBox_k_s.setProperty("value", 1.5)
        self.doubleSpinBox_k_s.setObjectName("doubleSpinBox_k_s")
        self.gridLayout.addWidget(self.doubleSpinBox_k_s, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.spinBox_N_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_N_2.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.spinBox_N_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_N_2.setMinimum(1)
        self.spinBox_N_2.setMaximum(20)
        self.spinBox_N_2.setProperty("value", 10)
        self.spinBox_N_2.setObjectName("spinBox_N_2")
        self.gridLayout.addWidget(self.spinBox_N_2, 7, 2, 1, 1)
        self.doubleSpinBox_B = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_B.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_B.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_B.setMinimum(1.0)
        self.doubleSpinBox_B.setMaximum(1000000.0)
        self.doubleSpinBox_B.setProperty("value", 6.0)
        self.doubleSpinBox_B.setObjectName("doubleSpinBox_B")
        self.gridLayout.addWidget(self.doubleSpinBox_B, 2, 2, 1, 1)
        self.spinBox_N_1 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_N_1.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.spinBox_N_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_N_1.setMinimum(1)
        self.spinBox_N_1.setMaximum(20)
        self.spinBox_N_1.setProperty("value", 12)
        self.spinBox_N_1.setObjectName("spinBox_N_1")
        self.gridLayout.addWidget(self.spinBox_N_1, 6, 2, 1, 1)
        self.doubleSpinBox_H = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_H.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_H.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_H.setMinimum(1.0)
        self.doubleSpinBox_H.setMaximum(1000000.0)
        self.doubleSpinBox_H.setProperty("value", 100.0)
        self.doubleSpinBox_H.setObjectName("doubleSpinBox_H")
        self.gridLayout.addWidget(self.doubleSpinBox_H, 1, 2, 1, 1)
        self.label_H = QtWidgets.QLabel(self.groupBox)
        self.label_H.setObjectName("label_H")
        self.gridLayout.addWidget(self.label_H, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBox_Rb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_Rb.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Rb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Rb.setDecimals(4)
        self.doubleSpinBox_Rb.setMinimum(0.0)
        self.doubleSpinBox_Rb.setMaximum(100.0)
        self.doubleSpinBox_Rb.setProperty("value", 0.015)
        self.doubleSpinBox_Rb.setObjectName("doubleSpinBox_Rb")
        self.gridLayout.addWidget(self.doubleSpinBox_Rb, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.doubleSpinBox_Tg = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_Tg.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Tg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Tg.setDecimals(2)
        self.doubleSpinBox_Tg.setMinimum(-273.15)
        self.doubleSpinBox_Tg.setMaximum(100.0)
        self.doubleSpinBox_Tg.setProperty("value", 10.0)
        self.doubleSpinBox_Tg.setObjectName("doubleSpinBox_Tg")
        self.gridLayout.addWidget(self.doubleSpinBox_Tg, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.checkBox_CalcDepth = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_CalcDepth.setObjectName("checkBox_CalcDepth")
        self.gridLayout.addWidget(self.checkBox_CalcDepth, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.doubleSpinBox_TMax = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_TMax.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_TMax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_TMax.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_TMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_TMax.setMinimum(-273.0)
        self.doubleSpinBox_TMax.setMaximum(1000.0)
        self.doubleSpinBox_TMax.setProperty("value", 16.0)
        self.doubleSpinBox_TMax.setObjectName("doubleSpinBox_TMax")
        self.gridLayout_5.addWidget(self.doubleSpinBox_TMax, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(445, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 3, 0, 1, 1)
        self.spinBox_Years = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_Years.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBox_Years.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_Years.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.spinBox_Years.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_Years.setMinimum(1)
        self.spinBox_Years.setMaximum(20)
        self.spinBox_Years.setProperty("value", 20)
        self.spinBox_Years.setObjectName("spinBox_Years")
        self.gridLayout_5.addWidget(self.spinBox_Years, 3, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 0, 0, 1, 1)
        self.doubleSpinBox_TMin = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_TMin.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_TMin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_TMin.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_TMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_TMin.setMinimum(-273.0)
        self.doubleSpinBox_TMin.setMaximum(1000.0)
        self.doubleSpinBox_TMin.setObjectName("doubleSpinBox_TMin")
        self.gridLayout_5.addWidget(self.doubleSpinBox_TMin, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 516, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButton_NextGeneral = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_NextGeneral.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_NextGeneral.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_NextGeneral.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_NextGeneral.setObjectName("pushButton_NextGeneral")
        self.horizontalLayout_4.addWidget(self.pushButton_NextGeneral)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.scrollArea_General.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.scrollArea_General)
        self.stackedWidget.addWidget(self.page_General)
        self.page_thermal = QtWidgets.QWidget()
        self.page_thermal.setObjectName("page_thermal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_thermal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_thermal = QtWidgets.QScrollArea(self.page_thermal)
        self.scrollArea_thermal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_thermal.setLineWidth(0)
        self.scrollArea_thermal.setWidgetResizable(True)
        self.scrollArea_thermal.setObjectName("scrollArea_thermal")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 774, 753))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setStyleSheet("font: 75 16pt \"Arial\";")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_Hp_Mar = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Mar.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Mar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Mar.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Mar.setMinimum(0.0)
        self.doubleSpinBox_Hp_Mar.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Mar.setProperty("value", 102.0)
        self.doubleSpinBox_Hp_Mar.setObjectName("doubleSpinBox_Hp_Mar")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Mar, 4, 1, 1, 1)
        self.doubleSpinBox_Cp_Feb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Feb.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Feb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Feb.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Feb.setMinimum(0.0)
        self.doubleSpinBox_Cp_Feb.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Feb.setProperty("value", 0.0)
        self.doubleSpinBox_Cp_Feb.setObjectName("doubleSpinBox_Cp_Feb")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Feb, 3, 2, 1, 1)
        self.doubleSpinBox_Hp_Apr = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Apr.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Apr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Apr.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Apr.setMinimum(0.0)
        self.doubleSpinBox_Hp_Apr.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Apr.setProperty("value", 55.0)
        self.doubleSpinBox_Hp_Apr.setObjectName("doubleSpinBox_Hp_Apr")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Apr, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 13, 0, 1, 1)
        self.doubleSpinBox_Cp_Apr = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Apr.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Apr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Apr.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Apr.setMinimum(0.0)
        self.doubleSpinBox_Cp_Apr.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Apr.setProperty("value", 69.0)
        self.doubleSpinBox_Cp_Apr.setObjectName("doubleSpinBox_Cp_Apr")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Apr, 5, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 3, 1, 1)
        self.doubleSpinBox_Cp_May = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_May.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_May.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_May.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_May.setMinimum(0.0)
        self.doubleSpinBox_Cp_May.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_May.setProperty("value", 133.0)
        self.doubleSpinBox_Cp_May.setObjectName("doubleSpinBox_Cp_May")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_May, 6, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.doubleSpinBox_Hp_Jan = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Jan.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Jan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Jan.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Jan.setMinimum(0.0)
        self.doubleSpinBox_Hp_Jan.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Jan.setProperty("value", 160.0)
        self.doubleSpinBox_Hp_Jan.setObjectName("doubleSpinBox_Hp_Jan")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Jan, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 10, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 0, 1, 1)
        self.doubleSpinBox_Cp_Jan = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Jan.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Jan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Jan.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Jan.setMinimum(0.0)
        self.doubleSpinBox_Cp_Jan.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Jan.setProperty("value", 0.0)
        self.doubleSpinBox_Cp_Jan.setObjectName("doubleSpinBox_Cp_Jan")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Jan, 2, 2, 1, 1)
        self.doubleSpinBox_Hp_Feb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Feb.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Feb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Feb.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Feb.setMinimum(0.0)
        self.doubleSpinBox_Hp_Feb.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Feb.setProperty("value", 142.0)
        self.doubleSpinBox_Hp_Feb.setObjectName("doubleSpinBox_Hp_Feb")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Feb, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 8, 0, 1, 1)
        self.doubleSpinBox_Hp_May = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_May.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_May.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_May.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_May.setMinimum(0.0)
        self.doubleSpinBox_Hp_May.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_May.setProperty("value", 0.0)
        self.doubleSpinBox_Hp_May.setObjectName("doubleSpinBox_Hp_May")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_May, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 7, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 11, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 12, 0, 1, 1)
        self.doubleSpinBox_Cp_Mar = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Mar.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Mar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Mar.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Mar.setMinimum(0.0)
        self.doubleSpinBox_Cp_Mar.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Mar.setProperty("value", 34.0)
        self.doubleSpinBox_Cp_Mar.setObjectName("doubleSpinBox_Cp_Mar")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Mar, 4, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 4, 1, 1)
        self.doubleSpinBox_HL_Jan = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Jan.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Jan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Jan.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Jan.setDecimals(0)
        self.doubleSpinBox_HL_Jan.setMinimum(0.0)
        self.doubleSpinBox_HL_Jan.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Jan.setProperty("value", 46500.0)
        self.doubleSpinBox_HL_Jan.setObjectName("doubleSpinBox_HL_Jan")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Jan, 2, 3, 1, 1)
        self.doubleSpinBox_CL_Jan = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Jan.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Jan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Jan.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Jan.setDecimals(0)
        self.doubleSpinBox_CL_Jan.setMinimum(0.0)
        self.doubleSpinBox_CL_Jan.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Jan.setProperty("value", 4000.0)
        self.doubleSpinBox_CL_Jan.setObjectName("doubleSpinBox_CL_Jan")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Jan, 2, 4, 1, 1)
        self.doubleSpinBox_HL_Feb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Feb.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Feb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Feb.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Feb.setDecimals(0)
        self.doubleSpinBox_HL_Feb.setMinimum(0.0)
        self.doubleSpinBox_HL_Feb.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Feb.setProperty("value", 44400.0)
        self.doubleSpinBox_HL_Feb.setObjectName("doubleSpinBox_HL_Feb")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Feb, 3, 3, 1, 1)
        self.doubleSpinBox_HL_Mar = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Mar.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Mar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Mar.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Mar.setDecimals(0)
        self.doubleSpinBox_HL_Mar.setMinimum(0.0)
        self.doubleSpinBox_HL_Mar.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Mar.setProperty("value", 37500.0)
        self.doubleSpinBox_HL_Mar.setObjectName("doubleSpinBox_HL_Mar")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Mar, 4, 3, 1, 1)
        self.doubleSpinBox_HL_Apr = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Apr.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Apr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Apr.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Apr.setDecimals(0)
        self.doubleSpinBox_HL_Apr.setMinimum(0.0)
        self.doubleSpinBox_HL_Apr.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Apr.setProperty("value", 29700.0)
        self.doubleSpinBox_HL_Apr.setObjectName("doubleSpinBox_HL_Apr")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Apr, 5, 3, 1, 1)
        self.doubleSpinBox_HL_May = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_May.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_May.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_May.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_May.setDecimals(0)
        self.doubleSpinBox_HL_May.setMinimum(0.0)
        self.doubleSpinBox_HL_May.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_May.setProperty("value", 19200.0)
        self.doubleSpinBox_HL_May.setObjectName("doubleSpinBox_HL_May")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_May, 6, 3, 1, 1)
        self.doubleSpinBox_CL_Feb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Feb.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Feb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Feb.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Feb.setDecimals(0)
        self.doubleSpinBox_CL_Feb.setMinimum(0.0)
        self.doubleSpinBox_CL_Feb.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Feb.setProperty("value", 8000.0)
        self.doubleSpinBox_CL_Feb.setObjectName("doubleSpinBox_CL_Feb")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Feb, 3, 4, 1, 1)
        self.doubleSpinBox_CL_Mar = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Mar.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Mar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Mar.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Mar.setDecimals(0)
        self.doubleSpinBox_CL_Mar.setMinimum(0.0)
        self.doubleSpinBox_CL_Mar.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Mar.setProperty("value", 8000.0)
        self.doubleSpinBox_CL_Mar.setObjectName("doubleSpinBox_CL_Mar")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Mar, 4, 4, 1, 1)
        self.doubleSpinBox_CL_Apr = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Apr.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Apr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Apr.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Apr.setDecimals(0)
        self.doubleSpinBox_CL_Apr.setMinimum(0.0)
        self.doubleSpinBox_CL_Apr.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Apr.setProperty("value", 8000.0)
        self.doubleSpinBox_CL_Apr.setObjectName("doubleSpinBox_CL_Apr")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Apr, 5, 4, 1, 1)
        self.doubleSpinBox_CL_May = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_May.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_May.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_May.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_May.setDecimals(0)
        self.doubleSpinBox_CL_May.setMinimum(0.0)
        self.doubleSpinBox_CL_May.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_May.setProperty("value", 12000.0)
        self.doubleSpinBox_CL_May.setObjectName("doubleSpinBox_CL_May")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_May, 6, 4, 1, 1)
        self.doubleSpinBox_HL_Jun = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Jun.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Jun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Jun.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Jun.setDecimals(0)
        self.doubleSpinBox_HL_Jun.setMinimum(0.0)
        self.doubleSpinBox_HL_Jun.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Jun.setProperty("value", 0.0)
        self.doubleSpinBox_HL_Jun.setObjectName("doubleSpinBox_HL_Jun")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Jun, 7, 3, 1, 1)
        self.doubleSpinBox_CL_Jun = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Jun.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Jun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Jun.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Jun.setDecimals(0)
        self.doubleSpinBox_CL_Jun.setMinimum(0.0)
        self.doubleSpinBox_CL_Jun.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Jun.setProperty("value", 16000.0)
        self.doubleSpinBox_CL_Jun.setObjectName("doubleSpinBox_CL_Jun")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Jun, 7, 4, 1, 1)
        self.doubleSpinBox_HL_Jul = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Jul.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Jul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Jul.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Jul.setDecimals(0)
        self.doubleSpinBox_HL_Jul.setMinimum(0.0)
        self.doubleSpinBox_HL_Jul.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Jul.setProperty("value", 0.0)
        self.doubleSpinBox_HL_Jul.setObjectName("doubleSpinBox_HL_Jul")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Jul, 8, 3, 1, 1)
        self.doubleSpinBox_CL_Jul = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Jul.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Jul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Jul.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Jul.setDecimals(0)
        self.doubleSpinBox_CL_Jul.setMinimum(0.0)
        self.doubleSpinBox_CL_Jul.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Jul.setProperty("value", 32000.0)
        self.doubleSpinBox_CL_Jul.setObjectName("doubleSpinBox_CL_Jul")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Jul, 8, 4, 1, 1)
        self.doubleSpinBox_HL_Aug = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Aug.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Aug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Aug.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Aug.setDecimals(0)
        self.doubleSpinBox_HL_Aug.setMinimum(0.0)
        self.doubleSpinBox_HL_Aug.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Aug.setProperty("value", 0.0)
        self.doubleSpinBox_HL_Aug.setObjectName("doubleSpinBox_HL_Aug")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Aug, 9, 3, 1, 1)
        self.doubleSpinBox_CL_Aug = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Aug.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Aug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Aug.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Aug.setDecimals(0)
        self.doubleSpinBox_CL_Aug.setMinimum(0.0)
        self.doubleSpinBox_CL_Aug.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Aug.setProperty("value", 32000.0)
        self.doubleSpinBox_CL_Aug.setObjectName("doubleSpinBox_CL_Aug")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Aug, 9, 4, 1, 1)
        self.doubleSpinBox_HL_Sep = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Sep.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Sep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Sep.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Sep.setDecimals(0)
        self.doubleSpinBox_HL_Sep.setMinimum(0.0)
        self.doubleSpinBox_HL_Sep.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Sep.setProperty("value", 18300.0)
        self.doubleSpinBox_HL_Sep.setObjectName("doubleSpinBox_HL_Sep")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Sep, 10, 3, 1, 1)
        self.doubleSpinBox_CL_Sep = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Sep.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Sep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Sep.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Sep.setDecimals(0)
        self.doubleSpinBox_CL_Sep.setMinimum(0.0)
        self.doubleSpinBox_CL_Sep.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Sep.setProperty("value", 16000.0)
        self.doubleSpinBox_CL_Sep.setObjectName("doubleSpinBox_CL_Sep")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Sep, 10, 4, 1, 1)
        self.doubleSpinBox_HL_Oct = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Oct.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Oct.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Oct.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Oct.setDecimals(0)
        self.doubleSpinBox_HL_Oct.setMinimum(0.0)
        self.doubleSpinBox_HL_Oct.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Oct.setProperty("value", 26100.0)
        self.doubleSpinBox_HL_Oct.setObjectName("doubleSpinBox_HL_Oct")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Oct, 11, 3, 1, 1)
        self.doubleSpinBox_CL_Oct = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Oct.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Oct.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Oct.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Oct.setDecimals(0)
        self.doubleSpinBox_CL_Oct.setMinimum(0.0)
        self.doubleSpinBox_CL_Oct.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Oct.setProperty("value", 12000.0)
        self.doubleSpinBox_CL_Oct.setObjectName("doubleSpinBox_CL_Oct")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Oct, 11, 4, 1, 1)
        self.doubleSpinBox_HL_Dec = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Dec.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Dec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Dec.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Dec.setDecimals(0)
        self.doubleSpinBox_HL_Dec.setMinimum(0.0)
        self.doubleSpinBox_HL_Dec.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Dec.setProperty("value", 43200.0)
        self.doubleSpinBox_HL_Dec.setObjectName("doubleSpinBox_HL_Dec")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Dec, 13, 3, 1, 1)
        self.doubleSpinBox_CL_Dec = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Dec.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Dec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Dec.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Dec.setDecimals(0)
        self.doubleSpinBox_CL_Dec.setMinimum(0.0)
        self.doubleSpinBox_CL_Dec.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Dec.setProperty("value", 4000.0)
        self.doubleSpinBox_CL_Dec.setObjectName("doubleSpinBox_CL_Dec")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Dec, 13, 4, 1, 1)
        self.doubleSpinBox_HL_Nov = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_HL_Nov.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_HL_Nov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_HL_Nov.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_HL_Nov.setDecimals(0)
        self.doubleSpinBox_HL_Nov.setMinimum(0.0)
        self.doubleSpinBox_HL_Nov.setMaximum(10000000000.0)
        self.doubleSpinBox_HL_Nov.setProperty("value", 35100.0)
        self.doubleSpinBox_HL_Nov.setObjectName("doubleSpinBox_HL_Nov")
        self.gridLayout_2.addWidget(self.doubleSpinBox_HL_Nov, 12, 3, 1, 1)
        self.doubleSpinBox_CL_Nov = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_CL_Nov.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_CL_Nov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CL_Nov.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_CL_Nov.setDecimals(0)
        self.doubleSpinBox_CL_Nov.setMinimum(0.0)
        self.doubleSpinBox_CL_Nov.setMaximum(10000000000.0)
        self.doubleSpinBox_CL_Nov.setProperty("value", 8000.0)
        self.doubleSpinBox_CL_Nov.setObjectName("doubleSpinBox_CL_Nov")
        self.gridLayout_2.addWidget(self.doubleSpinBox_CL_Nov, 12, 4, 1, 1)
        self.doubleSpinBox_Hp_Jun = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Jun.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Jun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Jun.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Jun.setMinimum(0.0)
        self.doubleSpinBox_Hp_Jun.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Jun.setProperty("value", 0.0)
        self.doubleSpinBox_Hp_Jun.setObjectName("doubleSpinBox_Hp_Jun")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Jun, 7, 1, 1, 1)
        self.doubleSpinBox_Cp_Jun = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Jun.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Jun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Jun.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Jun.setMinimum(0.0)
        self.doubleSpinBox_Cp_Jun.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Jun.setProperty("value", 187.0)
        self.doubleSpinBox_Cp_Jun.setObjectName("doubleSpinBox_Cp_Jun")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Jun, 7, 2, 1, 1)
        self.doubleSpinBox_Hp_Jul = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Jul.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Jul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Jul.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Jul.setMinimum(0.0)
        self.doubleSpinBox_Hp_Jul.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Jul.setProperty("value", 0.0)
        self.doubleSpinBox_Hp_Jul.setObjectName("doubleSpinBox_Hp_Jul")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Jul, 8, 1, 1, 1)
        self.doubleSpinBox_Cp_Jul = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Jul.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Jul.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Jul.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Jul.setMinimum(0.0)
        self.doubleSpinBox_Cp_Jul.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Jul.setProperty("value", 213.0)
        self.doubleSpinBox_Cp_Jul.setObjectName("doubleSpinBox_Cp_Jul")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Jul, 8, 2, 1, 1)
        self.doubleSpinBox_Hp_Aug = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Aug.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Aug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Aug.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Aug.setMinimum(0.0)
        self.doubleSpinBox_Hp_Aug.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Aug.setProperty("value", 0.0)
        self.doubleSpinBox_Hp_Aug.setObjectName("doubleSpinBox_Hp_Aug")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Aug, 9, 1, 1, 1)
        self.doubleSpinBox_Cp_Aug = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Aug.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Aug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Aug.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Aug.setMinimum(0.0)
        self.doubleSpinBox_Cp_Aug.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Aug.setProperty("value", 240.0)
        self.doubleSpinBox_Cp_Aug.setObjectName("doubleSpinBox_Cp_Aug")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Aug, 9, 2, 1, 1)
        self.doubleSpinBox_Hp_Sep = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Sep.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Sep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Sep.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Sep.setMinimum(0.0)
        self.doubleSpinBox_Hp_Sep.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Sep.setProperty("value", 40.4)
        self.doubleSpinBox_Hp_Sep.setObjectName("doubleSpinBox_Hp_Sep")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Sep, 10, 1, 1, 1)
        self.doubleSpinBox_Cp_Sep = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Sep.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Sep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Sep.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Sep.setMinimum(0.0)
        self.doubleSpinBox_Cp_Sep.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Sep.setProperty("value", 160.0)
        self.doubleSpinBox_Cp_Sep.setObjectName("doubleSpinBox_Cp_Sep")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Sep, 10, 2, 1, 1)
        self.doubleSpinBox_Hp_Oct = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Oct.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Oct.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Oct.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Oct.setMinimum(0.0)
        self.doubleSpinBox_Hp_Oct.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Oct.setProperty("value", 85.0)
        self.doubleSpinBox_Hp_Oct.setObjectName("doubleSpinBox_Hp_Oct")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Oct, 11, 1, 1, 1)
        self.doubleSpinBox_Cp_Oct = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Oct.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Oct.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Oct.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Oct.setMinimum(0.0)
        self.doubleSpinBox_Cp_Oct.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Oct.setProperty("value", 37.0)
        self.doubleSpinBox_Cp_Oct.setObjectName("doubleSpinBox_Cp_Oct")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Oct, 11, 2, 1, 1)
        self.doubleSpinBox_Hp_Nov = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Nov.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Nov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Nov.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Nov.setMinimum(0.0)
        self.doubleSpinBox_Hp_Nov.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Nov.setProperty("value", 119.0)
        self.doubleSpinBox_Hp_Nov.setObjectName("doubleSpinBox_Hp_Nov")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Nov, 12, 1, 1, 1)
        self.doubleSpinBox_Cp_Nov = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Nov.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Nov.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Nov.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Nov.setMinimum(0.0)
        self.doubleSpinBox_Cp_Nov.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Nov.setProperty("value", 0.0)
        self.doubleSpinBox_Cp_Nov.setObjectName("doubleSpinBox_Cp_Nov")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Nov, 12, 2, 1, 1)
        self.doubleSpinBox_Hp_Dec = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Hp_Dec.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Hp_Dec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hp_Dec.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Hp_Dec.setMinimum(0.0)
        self.doubleSpinBox_Hp_Dec.setMaximum(1000000.0)
        self.doubleSpinBox_Hp_Dec.setProperty("value", 136.0)
        self.doubleSpinBox_Hp_Dec.setObjectName("doubleSpinBox_Hp_Dec")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Hp_Dec, 13, 1, 1, 1)
        self.doubleSpinBox_Cp_Dec = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_Cp_Dec.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(84, 188, 235);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.doubleSpinBox_Cp_Dec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Cp_Dec.setProperty("showGroupSeparator", True)
        self.doubleSpinBox_Cp_Dec.setMinimum(0.0)
        self.doubleSpinBox_Cp_Dec.setMaximum(1000000.0)
        self.doubleSpinBox_Cp_Dec.setProperty("value", 0.0)
        self.doubleSpinBox_Cp_Dec.setObjectName("doubleSpinBox_Cp_Dec")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Cp_Dec, 13, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_PreviousThermal = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_PreviousThermal.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_PreviousThermal.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_PreviousThermal.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_PreviousThermal.setObjectName("pushButton_PreviousThermal")
        self.horizontalLayout_5.addWidget(self.pushButton_PreviousThermal)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.scrollArea_thermal.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea_thermal)
        self.stackedWidget.addWidget(self.page_thermal)
        self.page_Results = QtWidgets.QWidget()
        self.page_Results.setObjectName("page_Results")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_Results)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_Res = QtWidgets.QScrollArea(self.page_Results)
        self.scrollArea_Res.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_Res.setLineWidth(0)
        self.scrollArea_Res.setWidgetResizable(True)
        self.scrollArea_Res.setObjectName("scrollArea_Res")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 774, 753))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_Size = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Size.sizePolicy().hasHeightForWidth())
        self.label_Size.setSizePolicy(sizePolicy)
        self.label_Size.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_Size.setObjectName("label_Size")
        self.horizontalLayout_9.addWidget(self.label_Size)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.pushButton_SaveData = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_SaveData.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_SaveData.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_SaveData.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_SaveData.setObjectName("pushButton_SaveData")
        self.horizontalLayout_9.addWidget(self.pushButton_SaveData)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_Legend = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_Legend.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_Legend.setChecked(True)
        self.checkBox_Legend.setTristate(False)
        self.checkBox_Legend.setObjectName("checkBox_Legend")
        self.horizontalLayout_10.addWidget(self.checkBox_Legend)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.pushButton_SaveFigure = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_SaveFigure.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_SaveFigure.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_SaveFigure.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_SaveFigure.setObjectName("pushButton_SaveFigure")
        self.horizontalLayout_10.addWidget(self.pushButton_SaveFigure)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.scrollArea_Res.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_Res)
        self.stackedWidget.addWidget(self.page_Results)
        self.gridLayout_3.addWidget(self.stackedWidget, 1, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_Status = QtWidgets.QLabel(GHEtool)
        self.label_Status.setObjectName("label_Status")
        self.horizontalLayout_7.addWidget(self.label_Status)
        self.progressBar = QtWidgets.QProgressBar(GHEtool)
        self.progressBar.setStyleSheet("QProgressBar{border: 1px solid white;\n"
" border-radius: 10px;\n"
"text-align: center;\n"
" color: #ffffff;\n"
"}QProgressBar::chunk{background-color: #54bceb; border-radius: 10px;}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_7.addWidget(self.progressBar)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_SaveScenariosExternal = QtWidgets.QPushButton(GHEtool)
        self.pushButton_SaveScenariosExternal.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_SaveScenariosExternal.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_SaveScenariosExternal.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_SaveScenariosExternal.setObjectName("pushButton_SaveScenariosExternal")
        self.horizontalLayout_2.addWidget(self.pushButton_SaveScenariosExternal)
        self.pushButton_LoadScenarios = QtWidgets.QPushButton(GHEtool)
        self.pushButton_LoadScenarios.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_LoadScenarios.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_LoadScenarios.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_LoadScenarios.setObjectName("pushButton_LoadScenarios")
        self.horizontalLayout_2.addWidget(self.pushButton_LoadScenarios)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.pushButton_Start = QtWidgets.QPushButton(GHEtool)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_Start.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_Start.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout_2.addWidget(self.pushButton_Start)
        self.pushButton_Cancel = QtWidgets.QPushButton(GHEtool)
        self.pushButton_Cancel.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_Cancel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_Cancel.setStyleSheet("*{border: 3px solid rgb(84, 188, 235);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 188, 235);\n"
"background-color: rgb(84, 188, 235);\n"
"font: 75 11pt \"Verdana\";}\n"
"*:hover{background-color: rgb(0, 64, 122);}")
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_Cancel)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)

        self.retranslateUi(GHEtool)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GHEtool)

    def retranslateUi(self, GHEtool):
        _translate = QtCore.QCoreApplication.translate
        GHEtool.setWindowTitle(_translate("GHEtool", "GHE tool"))
        self.pushButton_SaveScenario.setText(_translate("GHEtool", "Update Scenario"))
        self.pushButton_AddScenario.setText(_translate("GHEtool", "Add Scenario"))
        self.pushButton_DeleteScenario.setText(_translate("GHEtool", "Delete Scenario"))
        self.pushButton_General.setText(_translate("GHEtool", "General"))
        self.pushButton_thermalDemands.setText(_translate("GHEtool", "Thermal \n"
" demands"))
        self.pushButton_Results.setText(_translate("GHEtool", "Results"))
        self.label.setText(_translate("GHEtool", "General "))
        self.groupBox.setTitle(_translate("GHEtool", "General"))
        self.label_3.setText(_translate("GHEtool", "conductivity of the soil [W/mK]: "))
        self.label_7.setText(_translate("GHEtool", "length of rectangular field [#]: "))
        self.label_H.setText(_translate("GHEtool", "Borehole depth [m]: "))
        self.label_2.setText(_translate("GHEtool", "borehole spacing [m]: "))
        self.label_4.setText(_translate("GHEtool", "Ground temperature at infinity [°C]: "))
        self.label_5.setText(_translate("GHEtool", "Equivalent borehole resistance [mK/W]: "))
        self.label_6.setText(_translate("GHEtool", "width of rectangular field [#]: "))
        self.checkBox_CalcDepth.setText(_translate("GHEtool", "Determine the required depth"))
        self.groupBox_3.setTitle(_translate("GHEtool", "Temperature constraints and simulation period"))
        self.label_30.setText(_translate("GHEtool", "Simulation period [yrs]"))
        self.label_32.setText(_translate("GHEtool", "Maximal temperature [°C]"))
        self.label_31.setText(_translate("GHEtool", "Minimal temperature [°C]"))
        self.pushButton_NextGeneral.setText(_translate("GHEtool", "next ->"))
        self.label_28.setText(_translate("GHEtool", "Thermal demands"))
        self.groupBox_2.setTitle(_translate("GHEtool", "Thermal demands"))
        self.label_23.setText(_translate("GHEtool", "December"))
        self.label_19.setText(_translate("GHEtool", "August"))
        self.label_24.setText(_translate("GHEtool", "Heating Load"))
        self.label_10.setText(_translate("GHEtool", "[kW]"))
        self.label_11.setText(_translate("GHEtool", "peak Cooling"))
        self.label_9.setText(_translate("GHEtool", "peak Heating"))
        self.label_8.setText(_translate("GHEtool", "January"))
        self.label_20.setText(_translate("GHEtool", "September"))
        self.label_25.setText(_translate("GHEtool", "[kWh]"))
        self.label_15.setText(_translate("GHEtool", "April"))
        self.label_14.setText(_translate("GHEtool", "March"))
        self.label_13.setText(_translate("GHEtool", "Fabruary"))
        self.label_16.setText(_translate("GHEtool", "July"))
        self.label_12.setText(_translate("GHEtool", "[kW]"))
        self.label_18.setText(_translate("GHEtool", "May"))
        self.label_17.setText(_translate("GHEtool", "June"))
        self.label_22.setText(_translate("GHEtool", "October"))
        self.label_21.setText(_translate("GHEtool", "November"))
        self.label_26.setText(_translate("GHEtool", "Cooling Load"))
        self.label_27.setText(_translate("GHEtool", "[kWh]"))
        self.pushButton_PreviousThermal.setText(_translate("GHEtool", "<- previous"))
        self.label_Size.setText(_translate("GHEtool", "Size"))
        self.pushButton_SaveData.setText(_translate("GHEtool", "Save results"))
        self.checkBox_Legend.setText(_translate("GHEtool", "Show Legend?"))
        self.pushButton_SaveFigure.setText(_translate("GHEtool", "Save figure"))
        self.label_Status.setText(_translate("GHEtool", "Progress"))
        self.pushButton_SaveScenariosExternal.setText(_translate("GHEtool", "Save Scenarios \n"
" externaly"))
        self.pushButton_LoadScenarios.setText(_translate("GHEtool", "Load Scenarios \n"
" from extern"))
        self.pushButton_Start.setText(_translate("GHEtool", "Start"))
        self.pushButton_Cancel.setText(_translate("GHEtool", "Cancel"))

