from GHEtool.gui.gui_classes.gui_structure_classes.category import Category
from GHEtool.gui.gui_classes.gui_structure_classes.aim import Aim
from GHEtool.gui.gui_classes.gui_structure_classes.button_box import ButtonBox
from GHEtool.gui.gui_classes.gui_structure_classes.figure_option import FigureOption
from GHEtool.gui.gui_classes.gui_structure_classes.float_box import FloatBox
from GHEtool.gui.gui_classes.gui_structure_classes.filename_box import FileNameBox
from GHEtool.gui.gui_classes.gui_structure_classes.function_button import FunctionButton
from GHEtool.gui.gui_classes.gui_structure_classes.hint import Hint
from GHEtool.gui.gui_classes.gui_structure_classes.int_box import IntBox
from GHEtool.gui.gui_classes.gui_structure_classes.list_box import ListBox
from GHEtool.gui.gui_classes.gui_structure_classes.option import Option
from GHEtool.gui.gui_classes.gui_structure_classes.page import Page
from GHEtool.gui.gui_classes.gui_structure_classes.result_figure import ResultFigure
from GHEtool.gui.gui_classes.gui_structure_classes.result_text import ResultText